// Code generated by hand. Based on gomock patterns.

package observability

import (
	"context"
	"reflect"

	"go.opentelemetry.io/otel/trace"
	"go.uber.org/mock/gomock"
)

// MockInstrumenter is a mock of Instrumenter interface.
type MockInstrumenter struct {
	ctrl     *gomock.Controller
	recorder *MockInstrumenterMockRecorder
}

// MockInstrumenterMockRecorder is the mock recorder for MockInstrumenter.
type MockInstrumenterMockRecorder struct {
	mock *MockInstrumenter
}

// NewMockInstrumenter creates a new mock instance.
func NewMockInstrumenter(ctrl *gomock.Controller) *MockInstrumenter {
	mock := &MockInstrumenter{ctrl: ctrl}
	mock.recorder = &MockInstrumenterMockRecorder{mock}

	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInstrumenter) EXPECT() *MockInstrumenterMockRecorder {
	return m.recorder
}

// SetLogger mocks base method.
func (m *MockInstrumenter) SetLogger(l Logger) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetLogger", l)
}

// SetLogger indicates an expected call of SetLogger.
func (mr *MockInstrumenterMockRecorder) SetLogger(l any) *gomock.Call {
	mr.mock.ctrl.T.Helper()

	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLogger", reflect.TypeOf((*MockInstrumenter)(nil).SetLogger), l)
}

// SetMetrics mocks base method.
func (m *MockInstrumenter) SetMetrics(metrics Metrics) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetMetrics", metrics)
}

// SetMetrics indicates an expected call of SetMetrics.
func (mr *MockInstrumenterMockRecorder) SetMetrics(metrics any) *gomock.Call {
	mr.mock.ctrl.T.Helper()

	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMetrics", reflect.TypeOf((*MockInstrumenter)(nil).SetMetrics), metrics)
}

// SetTracer mocks base method.
func (m *MockInstrumenter) SetTracer(t trace.Tracer) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetTracer", t)
}

// SetTracer indicates an expected call of SetTracer.
func (mr *MockInstrumenterMockRecorder) SetTracer(t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()

	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTracer", reflect.TypeOf((*MockInstrumenter)(nil).SetTracer), t)
}

// Logf mocks base method.
func (m *MockInstrumenter) Logf(format string, args ...any) {
	m.ctrl.T.Helper()

	varargs := append([]any{format}, args...)

	m.ctrl.Call(m, "Logf", varargs...)
}

// Logf indicates an expected call of Logf.
func (mr *MockInstrumenterMockRecorder) Logf(format any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()

	varargs := append([]any{format}, args...)

	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logf", reflect.TypeOf((*MockInstrumenter)(nil).Logf), varargs...)
}

// Debugf mocks base method.
func (m *MockInstrumenter) Debugf(format string, args ...any) {
	m.ctrl.T.Helper()

	varargs := append([]any{format}, args...)

	m.ctrl.Call(m, "Debugf", varargs...)
}

// Debugf indicates an expected call of Debugf.
func (mr *MockInstrumenterMockRecorder) Debugf(format any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()

	varargs := append([]any{format}, args...)

	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Debugf", reflect.TypeOf((*MockInstrumenter)(nil).Debugf), varargs...)
}

// Errorf mocks base method.
func (m *MockInstrumenter) Errorf(format string, args ...any) {
	m.ctrl.T.Helper()

	varargs := append([]any{format}, args...)

	m.ctrl.Call(m, "Errorf", varargs...)
}

// Errorf indicates an expected call of Errorf.
func (mr *MockInstrumenterMockRecorder) Errorf(format any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()

	varargs := append([]any{format}, args...)

	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Errorf", reflect.TypeOf((*MockInstrumenter)(nil).Errorf), varargs...)
}

// RegisterStatsHistogram mocks base method.
func (m *MockInstrumenter) RegisterStatsHistogram(buckets ...float64) {
	m.ctrl.T.Helper()

	varargs := make([]any, 0, len(buckets))
	for _, a := range buckets {
		varargs = append(varargs, a)
	}

	m.ctrl.Call(m, "RegisterStatsHistogram", varargs...)
}

// RegisterStatsHistogram indicates an expected call of RegisterStatsHistogram.
func (mr *MockInstrumenterMockRecorder) RegisterStatsHistogram(buckets ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()

	return mr.mock.ctrl.RecordCallWithMethodType(
		mr.mock, "RegisterStatsHistogram", reflect.TypeOf((*MockInstrumenter)(nil).RegisterStatsHistogram), buckets...)
}

// InstrumentOperation mocks base method.
func (m *MockInstrumenter) InstrumentOperation(ctx context.Context, op ObservableQuery) (tracerCtx context.Context, end func()) {
	m.ctrl.T.Helper()

	ret := m.ctrl.Call(m, "InstrumentOperation", ctx, op)
	ret0, _ := ret[0].(context.Context)
	ret1, _ := ret[1].(func())

	return ret0, ret1
}

// InstrumentOperation indicates an expected call of InstrumentOperation.
func (mr *MockInstrumenterMockRecorder) InstrumentOperation(ctx, op any) *gomock.Call {
	mr.mock.ctrl.T.Helper()

	return mr.mock.ctrl.RecordCallWithMethodType(
		mr.mock, "InstrumentOperation", reflect.TypeOf((*MockInstrumenter)(nil).InstrumentOperation), ctx, op)
}
